### ISSUE TITLE
unknown build status

### ISSUE THREAD

**Issue by peisenha** [OpenSourceEconomics/project-description-numerical-integration#12]
Please fix the badge, https://github.com/OpenSourceEconomics/project-description-numerical-integration Probably just broken due to the renaming of the repo.

**Comment by rafaelsuchy** [comment]
Fixed in rafaelsuchy_new (will be merged into master as part of tackling #11)

**Comment by rafaelsuchy** [comment]
Will check whether link is still working after merging of [PR#13](https://github.com/OpenSourceEconomics/project-description-numerical-integration/pull/13)
